$(document).ready(function(){
	$('a>span:contains("ARI")').replaceWith('<img title="Arizona Cardinals" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/ari.png" width="37"></span>');
	$('a>span:contains("ATL")').replaceWith('<img title="Atlanta Falcons" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/atl.png" width="37"></span>');
	$('a>span:contains("BAL")').replaceWith('<img title="Baltimore Ravens" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/bal.png" width="37"></span>');
	$('a>span:contains("BUF")').replaceWith('<img title="Buffalo Bills" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/buf.png" width="37"></span>');
	$('a>span:contains("CAR")').replaceWith('<img title="Carolina Panthers" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/car.png" width="37"></span>');
	$('a>span:contains("CHI")').replaceWith('<img title="Chicago Bears" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/chi.png" width="37"></span>');
	$('a>span:contains("CIN")').replaceWith('<img title="Cincinnati Bengals" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/cin.png" width="37"></span>');
	$('a >span:contains("CLE")').replaceWith('<img title="Cleveland Browns" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/cle.png" width="37"></span>');
	$('a>span:contains("DAL")').replaceWith('<img title="Dallas Cowboys" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/dal.png" width="37"></span>');
	$('a>span:contains("DEN")').replaceWith('<img title="Denver Broncos" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/den.png" width="37"></span>');
	$('a>span:contains("DET")').replaceWith('<img title="Detroit Lions" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/det.png" width="37"></span>');
	$('a>span:contains("GB")').replaceWith('<img title="Green Bay Packers" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/gb.png" width="37"></span>');
	$('a>span:contains("HOU")').replaceWith('<img title="Houston Texans" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/hou.png" width="37"></span>');
	$('a>span:contains("IND")').replaceWith('<img title="Indianapolis Colts" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/ind.png" width="37"></span>');
	$('a>span:contains("JAX")').replaceWith('<img title="Jacksonville Jaguars" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/jax.png" width="37"></span>');
	$('a>span:contains("KC")').replaceWith('<img title="Kansas City Chiefs" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/kc.png" width="37"></span>');
	$('a>span:contains("MIA")').replaceWith('<img title="Miami Dolphins" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/mia.png" width="37"></span>');
	$('a>span:contains("MIN")').replaceWith('<img title="Minnesota Vikings" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/min.png" width="37"></span>');
	$('a>span:contains("NE")').replaceWith('<img title="New England Patriots" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/ne.png" width="37"></span>');
	$('a>span:contains("NO")').replaceWith('<img title="New Orleans Saints" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/no.png" width="37"></span>');
	$('a>span:contains("NYG")').replaceWith('<img title="New York Giants" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/nyg.png" width="37"></span>');
	$('a>span:contains("NYJ")').replaceWith('<img title="New York Jets" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/nyj.png" width="37"></span>');
	$('a>span:contains("OAK")').replaceWith('<img title="Oakland Raiders" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/oak.png" width="37"></span>');
	$('a>span:contains("PHI")').replaceWith('<img title="Philadelphia Eagles" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/phi.png" width="37"></span>');
	$('a>span:contains("PIT")').replaceWith('<img title="Pittsburgh Steelers" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/pit.png" width="37"></span>');
	$('a>span:contains("LAC")').replaceWith('<img title="Los Angeles Chargers" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/sd.png" width="37"></span>');
	$('a>span:contains("SF")').replaceWith('<img title="San Francisco 49ers" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/sf.png" width="37"></span>');
	$('a>span:contains("SEA")').replaceWith('<img title="Seattle Seahawks" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/sea.png" width="37"></span>');
	$('a>span:contains("LAR")').replaceWith('<img title="Los Angeles Rams" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/stl.png" width="37"></span>');
	$('a>span:contains("TB")').replaceWith('<img title="Tampa Bay Buccaneers" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/tb.png" width="37"></span>');
	$('a>span:contains("TEN")').replaceWith('<img title="Tennessee Titans" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/ten.png" width="37"></span>');
	$('a>span:contains("WAS")').replaceWith('<img title="Washington Redskins" src="http://i.nflcdn.com/static/site/7.5/img/logos/teams-gloss-81x54/was.png" width="37"></span>');
	$("#daddyleagues-menu .navbar .nav > li:contains('Forum')").replaceWith('<li class><a href="http://maddenps4spain.freeforums.org/index.php">Forum</a></li>');
	$('.data-table1 td:contains("Cardinals")').prepend('<img src="https://static.nfl.com/static/site/img/teams/ARZ/ARZ_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("arz");
	$('.data-table1 td:contains("Falcons")').prepend('<img src="https://static.nfl.com/static/site/img/teams/ATL/ATL_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("atl");
	$('.data-table1 td:contains("Ravens")').prepend('<img src="https://static.nfl.com/static/site/img/teams/BAL/BAL_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("bal");
	$('.data-table1 td:contains("Bills")').prepend('<img src="https://static.nfl.com/static/site/img/teams/BUF/BUF_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("buf");
	$('.data-table1 td:contains("Panthers")').prepend('<img src="https://static.nfl.com/static/site/img/teams/CAR/CAR_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("car");
	$('.data-table1 td:contains("Bears")').prepend('<img src="https://static.nfl.com/static/site/img/teams/CHI/CHI_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("chi");
	$('.data-table1 td:contains("Bengals")').prepend('<img src="https://static.nfl.com/static/site/img/teams/CIN/CIN_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("cin");
	$('.data-table1 td:contains("Browns")').prepend('<img src="https://static.nfl.com/static/site/img/teams/CLE/CLE_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("cle");
	$('.data-table1 td:contains("Cowboys")').prepend('<img src="https://static.nfl.com/static/site/img/teams/DAL/DAL_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("dal");
	$('.data-table1 td:contains("Broncos")').prepend('<img src="https://static.nfl.com/static/site/img/teams/DEN/DEN_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("den");
	$('.data-table1 td:contains("Lions")').prepend('<img src="https://static.nfl.com/static/site/img/teams/DET/DET_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("det");
	$('.data-table1 td:contains("Packers")').prepend('<img src="https://static.nfl.com/static/site/img/teams/GB/GB_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("gb");
	$('.data-table1 td:contains("Texans")').prepend('<img src="https://static.nfl.com/static/site/img/teams/HOU/HOU_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("hou");
	$('.data-table1 td:contains("Colts")').prepend('<img src="https://static.nfl.com/static/site/img/teams/IND/IND_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("ind");
	$('.data-table1 td:contains("Jaguars")').prepend('<img src="https://static.nfl.com/static/site/img/teams/JAC/JAC_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("jac");
	$('.data-table1 td:contains("Chiefs")').prepend('<img src="https://static.nfl.com/static/site/img/teams/KC/KC_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("kc");
	$('.data-table1 td:contains("Dolphins")').prepend('<img src="https://static.nfl.com/static/site/img/teams/MIA/MIA_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("mia");
	$('.data-table1 td:contains("Vikings")').prepend('<img src="https://static.nfl.com/static/site/img/teams/MIN/MIN_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("min");
	$('.data-table1 td:contains("Patriots")').prepend('<img src="https://static.nfl.com/static/site/img/teams/NE/NE_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("ne");
	$('.data-table1 td:contains("Saints")').prepend('<img src="https://static.nfl.com/static/site/img/teams/NO/NO_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("no");
	$('.data-table1 td:contains("Giants")').prepend('<img src="https://static.nfl.com/static/site/img/teams/NYG/NYG_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("nyg");
	$('.data-table1 td:contains("Jets")').prepend('<img src="https://static.nfl.com/static/site/img/teams/NYJ/NYJ_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("nyj");
	$('.data-table1 td:contains("Raiders")').prepend('<img src="https://static.nfl.com/static/site/img/teams/OAK/OAK_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("oak");
	$('.data-table1 td:contains("Eagles")').prepend('<img src="https://static.nfl.com/static/site/img/teams/PHI/PHI_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("phi");
	$('.data-table1 td:contains("Steelers")').prepend('<img src="https://static.nfl.com/static/site/img/teams/PIT/PIT_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("pit");
	$('.data-table1 td:contains("Chargers")').prepend('<img src="https://static.nfl.com/static/site/img/teams/SD/SD_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("lac");
	$('.data-table1 td:contains("49ers")').prepend('<img src="https://static.nfl.com/static/site/img/teams/SF/SF_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("sf");
	$('.data-table1 td:contains("Seahawks")').prepend('<img src="https://static.nfl.com/static/site/img/teams/SEA/SEA_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("sea");
	$('.data-table1 td:contains("Rams")').prepend('<img src="https://static.nfl.com/static/site/img/teams/LA/LA_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("lar");
	$('.data-table1 td:contains("Buccaneers")').prepend('<img src="https://static.nfl.com/static/site/img/teams/TB/TB_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("tb");
	$('.data-table1 td:contains("Titans")').prepend('<img src="https://static.nfl.com/static/site/img/teams/TEN/TEN_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("ten");
	$('.data-table1 td:contains("Redskins")').prepend('<img src="https://static.nfl.com/static/site/img/teams/WAS/WAS_logo-20x20.gif" width="20" height="20" border="0" alt="Team logo" class="teamLogo"> </img>').addClass("was");
});