/**TeamBars Matchup**/
jQuery(function($) { 
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/6.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/6.png"]').before('<div class="teambar-ari"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/13.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/13.png"]').before('<div class="teambar-atl"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/24.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/24.png"]').before('<div class="teambar-bal"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/2.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/2.png"]').before('<div class="teambar-buf"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/20.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/20.png"]').before('<div class="teambar-car"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/0.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/0.png"]').before('<div class="teambar-chi"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/1.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/1.png"]').before('<div class="teambar-cin"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/4.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/4.png"]').before('<div class="teambar-cle"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/10.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/10.png"]').before('<div class="teambar-dal"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/3.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/3.png"]').before('<div class="teambar-den"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/18.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/18.png"]').before('<div class="teambar-det"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/19.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/19.png"]').before('<div class="teambar-gb"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/31.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/31.png"]').before('<div class="teambar-hou"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/9.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/9.png"]').before('<div class="teambar-ind"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/16.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/16.png"]').before('<div class="teambar-jac"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/8.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/8.png"]').before('<div class="teambar-kc"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/7.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/7.png"]').before('<div class="teambar-lac"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/23.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/23.png"]').before('<div class="teambar-lar"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/11.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/11.png"]').before('<div class="teambar-mia"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/30.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/30.png"]').before('<div class="teambar-min"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/21.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/21.png"]').before('<div class="teambar-ne"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/26.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/26.png"]').before('<div class="teambar-no"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/15.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/15.png"]').before('<div class="teambar-nyg"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/17.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/17.png"]').before('<div class="teambar-nyj"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/22.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/22.png"]').before('<div class="teambar-oak"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/12.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/12.png"]').before('<div class="teambar-phi"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/28.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/28.png"]').before('<div class="teambar-pit"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/14.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/14.png"]').before('<div class="teambar-sf"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/27.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/27.png"]').before('<div class="teambar-sea"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/5.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/5.png"]').before('<div class="teambar-tb"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/29.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/29.png"]').before('<div class="teambar-ten"></div>');
	$('div.cfm-player-team img[src*="/img/nfl/teams/left/25.png"], div.Teamcolors div.cfm-team-logo img[src*="/img/nfl/teams/left/25.png"]').before('<div class="teambar-was"></div>');

	//$('div.cfm-player-img').addClass("bg-white");
	$('span.pull-right:contains("Contract")').addClass("player-contract");
	$('div.cfm-player-info:contains("O. Scheme:")').addClass("team-main-page");
	$('span.pull-right:contains("OVR")').addClass("team-ovr Teamcolors");
	$('div.panel-body').addClass("Teamcolors");
	$('div.panel-body.Teamcolors .row').addClass("Teamcolors");

	var media = $('span.pull-right:contains("OVR")').text();
	media = media.substring(0,3) + ' OVR';
	$('span.pull-right:contains("OVR")').text(media);

	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/6.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-ari');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/13.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-atl');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/24.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-bal');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/2.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-buf');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/20.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-car');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/0.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-chi');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/1.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-cin');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/4.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-cle');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/10.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-dal');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/3.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-den');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/18.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-det');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/19.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-gb');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/31.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-hou');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/9.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-ind');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/16.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-jac');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/8.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-kc');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/7.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-lac');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/23.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-lar');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/11.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-mia');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/30.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-min');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/21.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-ne');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/26.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-no');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/15.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-nyg');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/17.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-nyj');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/22.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-oak');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/12.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-phi');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/28.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-pit');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/14.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-sf');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/27.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-sea');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/5.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-tb');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/29.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-ten');
	$('div.cfm-team-logo img[src*="/img/nfl/teams/left/25.png"]').parents('.cfm-player-profile.Teamcolors').addClass('team-was');

	$('.cfm-player-wrapper .panel-heading strong').first().text('TEAM RANKINGS');
	$('.cfm-player-wrapper .panel-heading strong').first().addClass('tituloRanking');
	$('.cfm-player-wrapper .panel-heading .salary-info strong').first().text('Salary');
	$('.cfm-player-wrapper .panel-heading .salary-info strong').first().removeClass('tituloRanking');
});